version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: composer install
      # Fake build.
      - run: echo "Build finished"

  security:
    docker:
      - image: circleci/php:latest
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: composer require --dev roave/security-advisories:dev-master

  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      # Fake deploy
      - run: echo "deploy finished"

workflows:
  version: 2
  build-scan-and-deploy:
    jobs:
      - build
      - security:
          requires:
            - build
      - deploy:
          requires:
            - security
